apiVersion: v1
kind: Service
metadata:
  name: wordpress
spec:
  type: {{ .Values.wordpress.serviceType }}
  ports:
    - port: 80
      nodePort: {{ .Values.wordpress.nodePort }}
  selector:
    app: wordpress
